# Generated by Django 4.1.7 on 2023-03-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disign_shop', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='colours',
            new_name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_colour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_material',
        ),
    ]
