# Generated by Django 4.1.7 on 2023-03-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('hash', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('hash', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FurniturePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('main_photo', models.URLField(max_length=500)),
                ('thumbnail_photo', models.URLField(max_length=500)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniture_shop.category')),
                ('colors', models.ManyToManyField(through='furniture_shop.Availability', to='furniture_shop.furniturecolor')),
                ('gallery', models.ManyToManyField(to='furniture_shop.furniturephoto')),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniture_shop.furniturecolor'),
        ),
        migrations.AddField(
            model_name='availability',
            name='furniture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniture_shop.furniture'),
        ),
    ]
