# Generated by Django 4.1.7 on 2023-03-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Availability',
            new_name='ColorAvailability',
        ),
    ]
