# Generated by Django 4.1.7 on 2023-03-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_shop', '0002_rename_availability_coloravailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='hash',
        ),
    ]
