# Generated by Django 4.1.7 on 2023-03-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_shop', '0003_remove_category_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
