# Generated by Django 4.1.7 on 2023-03-24 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_shop', '0004_furniture_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='furniture',
            name='depth',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='furniture',
            name='height',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='furniture',
            name='width',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coloravailability',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='furniture_shop.furniturecolor'),
        ),
        migrations.AlterField(
            model_name='coloravailability',
            name='furniture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='furniture_shop.furniture'),
        ),
    ]
